//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace final_android.net.azurewebsites.wsnutricion {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsDietaSoap", Namespace="http://tempuri.org/")]
    public partial class wsDieta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback consultaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaProgresoOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback insertarProgresoOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculoIMCOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculoTMBOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculoIdealOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculoCompCorporalOperationCompleted;
        
        private System.Threading.SendOrPostCallback calculoDieta_planOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsDieta() {
            this.Url = "http://wsnutricion.azurewebsites.net/wsDieta.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event consultaUsuarioCompletedEventHandler consultaUsuarioCompleted;
        
        /// <remarks/>
        public event consultaProgresoCompletedEventHandler consultaProgresoCompleted;
        
        /// <remarks/>
        public event insertarUsuarioCompletedEventHandler insertarUsuarioCompleted;
        
        /// <remarks/>
        public event insertarProgresoCompletedEventHandler insertarProgresoCompleted;
        
        /// <remarks/>
        public event calculoIMCCompletedEventHandler calculoIMCCompleted;
        
        /// <remarks/>
        public event calculoTMBCompletedEventHandler calculoTMBCompleted;
        
        /// <remarks/>
        public event calculoIdealCompletedEventHandler calculoIdealCompleted;
        
        /// <remarks/>
        public event calculoCompCorporalCompletedEventHandler calculoCompCorporalCompleted;
        
        /// <remarks/>
        public event calculoDieta_planCompletedEventHandler calculoDieta_planCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet consultaUsuario(string id) {
            object[] results = this.Invoke("consultaUsuario", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(string id) {
            this.consultaUsuarioAsync(id, null);
        }
        
        /// <remarks/>
        public void consultaUsuarioAsync(string id, object userState) {
            if ((this.consultaUsuarioOperationCompleted == null)) {
                this.consultaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaUsuarioOperationCompleted);
            }
            this.InvokeAsync("consultaUsuario", new object[] {
                        id}, this.consultaUsuarioOperationCompleted, userState);
        }
        
        private void OnconsultaUsuarioOperationCompleted(object arg) {
            if ((this.consultaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaUsuarioCompleted(this, new consultaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/consultaProgreso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet consultaProgreso(int id) {
            object[] results = this.Invoke("consultaProgreso", new object[] {
                        id});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void consultaProgresoAsync(int id) {
            this.consultaProgresoAsync(id, null);
        }
        
        /// <remarks/>
        public void consultaProgresoAsync(int id, object userState) {
            if ((this.consultaProgresoOperationCompleted == null)) {
                this.consultaProgresoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaProgresoOperationCompleted);
            }
            this.InvokeAsync("consultaProgreso", new object[] {
                        id}, this.consultaProgresoOperationCompleted, userState);
        }
        
        private void OnconsultaProgresoOperationCompleted(object arg) {
            if ((this.consultaProgresoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaProgresoCompleted(this, new consultaProgresoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertarUsuario(string correo, string contrasena, string nombreusuario, int peso, int altura, int sexo, int frecuencia, float tmb, float imc, int edad, int kxp, string corporal) {
            this.Invoke("insertarUsuario", new object[] {
                        correo,
                        contrasena,
                        nombreusuario,
                        peso,
                        altura,
                        sexo,
                        frecuencia,
                        tmb,
                        imc,
                        edad,
                        kxp,
                        corporal});
        }
        
        /// <remarks/>
        public void insertarUsuarioAsync(string correo, string contrasena, string nombreusuario, int peso, int altura, int sexo, int frecuencia, float tmb, float imc, int edad, int kxp, string corporal) {
            this.insertarUsuarioAsync(correo, contrasena, nombreusuario, peso, altura, sexo, frecuencia, tmb, imc, edad, kxp, corporal, null);
        }
        
        /// <remarks/>
        public void insertarUsuarioAsync(string correo, string contrasena, string nombreusuario, int peso, int altura, int sexo, int frecuencia, float tmb, float imc, int edad, int kxp, string corporal, object userState) {
            if ((this.insertarUsuarioOperationCompleted == null)) {
                this.insertarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarUsuarioOperationCompleted);
            }
            this.InvokeAsync("insertarUsuario", new object[] {
                        correo,
                        contrasena,
                        nombreusuario,
                        peso,
                        altura,
                        sexo,
                        frecuencia,
                        tmb,
                        imc,
                        edad,
                        kxp,
                        corporal}, this.insertarUsuarioOperationCompleted, userState);
        }
        
        private void OninsertarUsuarioOperationCompleted(object arg) {
            if ((this.insertarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/insertarProgreso", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void insertarProgreso(int id, int progreso_peso, int progreso_imc) {
            this.Invoke("insertarProgreso", new object[] {
                        id,
                        progreso_peso,
                        progreso_imc});
        }
        
        /// <remarks/>
        public void insertarProgresoAsync(int id, int progreso_peso, int progreso_imc) {
            this.insertarProgresoAsync(id, progreso_peso, progreso_imc, null);
        }
        
        /// <remarks/>
        public void insertarProgresoAsync(int id, int progreso_peso, int progreso_imc, object userState) {
            if ((this.insertarProgresoOperationCompleted == null)) {
                this.insertarProgresoOperationCompleted = new System.Threading.SendOrPostCallback(this.OninsertarProgresoOperationCompleted);
            }
            this.InvokeAsync("insertarProgreso", new object[] {
                        id,
                        progreso_peso,
                        progreso_imc}, this.insertarProgresoOperationCompleted, userState);
        }
        
        private void OninsertarProgresoOperationCompleted(object arg) {
            if ((this.insertarProgresoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.insertarProgresoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calculoIMC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double calculoIMC(int peso, int altura) {
            object[] results = this.Invoke("calculoIMC", new object[] {
                        peso,
                        altura});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void calculoIMCAsync(int peso, int altura) {
            this.calculoIMCAsync(peso, altura, null);
        }
        
        /// <remarks/>
        public void calculoIMCAsync(int peso, int altura, object userState) {
            if ((this.calculoIMCOperationCompleted == null)) {
                this.calculoIMCOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculoIMCOperationCompleted);
            }
            this.InvokeAsync("calculoIMC", new object[] {
                        peso,
                        altura}, this.calculoIMCOperationCompleted, userState);
        }
        
        private void OncalculoIMCOperationCompleted(object arg) {
            if ((this.calculoIMCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculoIMCCompleted(this, new calculoIMCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calculoTMB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double calculoTMB(int sexo, int altura, int peso, int frecuencia, int edad, int kxp) {
            object[] results = this.Invoke("calculoTMB", new object[] {
                        sexo,
                        altura,
                        peso,
                        frecuencia,
                        edad,
                        kxp});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void calculoTMBAsync(int sexo, int altura, int peso, int frecuencia, int edad, int kxp) {
            this.calculoTMBAsync(sexo, altura, peso, frecuencia, edad, kxp, null);
        }
        
        /// <remarks/>
        public void calculoTMBAsync(int sexo, int altura, int peso, int frecuencia, int edad, int kxp, object userState) {
            if ((this.calculoTMBOperationCompleted == null)) {
                this.calculoTMBOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculoTMBOperationCompleted);
            }
            this.InvokeAsync("calculoTMB", new object[] {
                        sexo,
                        altura,
                        peso,
                        frecuencia,
                        edad,
                        kxp}, this.calculoTMBOperationCompleted, userState);
        }
        
        private void OncalculoTMBOperationCompleted(object arg) {
            if ((this.calculoTMBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculoTMBCompleted(this, new calculoTMBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calculoIdeal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double calculoIdeal(int altura, int sexo) {
            object[] results = this.Invoke("calculoIdeal", new object[] {
                        altura,
                        sexo});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void calculoIdealAsync(int altura, int sexo) {
            this.calculoIdealAsync(altura, sexo, null);
        }
        
        /// <remarks/>
        public void calculoIdealAsync(int altura, int sexo, object userState) {
            if ((this.calculoIdealOperationCompleted == null)) {
                this.calculoIdealOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculoIdealOperationCompleted);
            }
            this.InvokeAsync("calculoIdeal", new object[] {
                        altura,
                        sexo}, this.calculoIdealOperationCompleted, userState);
        }
        
        private void OncalculoIdealOperationCompleted(object arg) {
            if ((this.calculoIdealCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculoIdealCompleted(this, new calculoIdealCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calculoCompCorporal", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string calculoCompCorporal(double imc) {
            object[] results = this.Invoke("calculoCompCorporal", new object[] {
                        imc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void calculoCompCorporalAsync(double imc) {
            this.calculoCompCorporalAsync(imc, null);
        }
        
        /// <remarks/>
        public void calculoCompCorporalAsync(double imc, object userState) {
            if ((this.calculoCompCorporalOperationCompleted == null)) {
                this.calculoCompCorporalOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculoCompCorporalOperationCompleted);
            }
            this.InvokeAsync("calculoCompCorporal", new object[] {
                        imc}, this.calculoCompCorporalOperationCompleted, userState);
        }
        
        private void OncalculoCompCorporalOperationCompleted(object arg) {
            if ((this.calculoCompCorporalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculoCompCorporalCompleted(this, new calculoCompCorporalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/calculoDieta_plan", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int calculoDieta_plan(double tmb_dieta) {
            object[] results = this.Invoke("calculoDieta_plan", new object[] {
                        tmb_dieta});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void calculoDieta_planAsync(double tmb_dieta) {
            this.calculoDieta_planAsync(tmb_dieta, null);
        }
        
        /// <remarks/>
        public void calculoDieta_planAsync(double tmb_dieta, object userState) {
            if ((this.calculoDieta_planOperationCompleted == null)) {
                this.calculoDieta_planOperationCompleted = new System.Threading.SendOrPostCallback(this.OncalculoDieta_planOperationCompleted);
            }
            this.InvokeAsync("calculoDieta_plan", new object[] {
                        tmb_dieta}, this.calculoDieta_planOperationCompleted, userState);
        }
        
        private void OncalculoDieta_planOperationCompleted(object arg) {
            if ((this.calculoDieta_planCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.calculoDieta_planCompleted(this, new calculoDieta_planCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultaUsuarioCompletedEventHandler(object sender, consultaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void consultaProgresoCompletedEventHandler(object sender, consultaProgresoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaProgresoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaProgresoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void insertarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void insertarProgresoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void calculoIMCCompletedEventHandler(object sender, calculoIMCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculoIMCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculoIMCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void calculoTMBCompletedEventHandler(object sender, calculoTMBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculoTMBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculoTMBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void calculoIdealCompletedEventHandler(object sender, calculoIdealCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculoIdealCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculoIdealCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void calculoCompCorporalCompletedEventHandler(object sender, calculoCompCorporalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculoCompCorporalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculoCompCorporalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void calculoDieta_planCompletedEventHandler(object sender, calculoDieta_planCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class calculoDieta_planCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal calculoDieta_planCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591